= Contributing to the Tutorial

== Contributing

Like every other open source project, we gladly accept
contributions. Sections that need help have been marked with
FIXMEs. All contributions will be duly credited in the credits page.

This document's source is maintained in a public git repo located at
https://github.com/bravegnu/gnu-eprog To contribute to the project,
fork the project on github and send in a pull request.

The document is written in
http://www.methods.co.nz/asciidoc/[asciidoc], and converted to HTML
using the http://docbook.sourceforge.net/[docbook-xsl] stylesheets.

  * Fork this repo into your GitHub account.
  
  * Install required software, for Debian / Ubuntu, use the following command.
+
------
sudo apt install asciidoc docbook libsaxon-java libxslthl-java imgsizer dia
------
+
  * Clone your repo.
+
------
git clone -o gh https://github.com/yourname/gnu-eprog
cd gnu-eprog
------
+
  * Make your changes.
  
  * Push you changes with `git`. Do use desriptive comments in your
    commits.

  * Send pull request to `gnu-eprog` maintainer, to review your
    changes and merge them into `master` `gnu-eprog` branch.
